name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or your version

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: npm run deploy
        env:
          CI: false
